/**
 * Offline teacher QA fixtures (10 DSE-style Straight Line MC patterns).
 * Used for UI/renderer QA without calling Gemini. Not for classroom distribution as “real papers”.
 */
export const QA_FIXTURES = [
  {
    id: 1,
    difficulty: 'Easy',
    subtopic: 'slope_intercepts',
    needs_graph: true,
    graph: {
      x_min: -6, x_max: 6, y_min: -6, y_max: 6,
      lines: [{ id: 'L', A: 1, B: -2, C: 2, label: 'L' }],
      points: [],
    },
    stem_latex: 'The figure shows the straight line $L$. The slope of $L$ is',
    options: [
      { key: 'A', latex: '$-2$' },
      { key: 'B', latex: '$-\\dfrac{1}{2}$' },
      { key: 'C', latex: '$\\dfrac{1}{2}$' },
      { key: 'D', latex: '$2$' },
    ],
    correct_key: 'C',
    smart_solution_latex: 'From $x-2y+2=0$, $y=\\frac{1}{2}x+1$. Slope $=\\frac{1}{2}$. Hence the answer is C.',
    common_traps: ['Using $-A/B$ with wrong sign', 'Reading rise/run inverted'],
  },
  {
    id: 2,
    difficulty: 'Easy',
    subtopic: 'slope_intercepts',
    needs_graph: true,
    graph: {
      x_min: -8, x_max: 8, y_min: -8, y_max: 8,
      lines: [{ id: 'L', A: 2, B: 1, C: -6, label: 'L' }],
      points: [],
    },
    stem_latex: 'The figure shows the straight line $L: 2x+y-6=0$. The $y$-intercept of $L$ is',
    options: [
      { key: 'A', latex: '$-6$' },
      { key: 'B', latex: '$-3$' },
      { key: 'C', latex: '$3$' },
      { key: 'D', latex: '$6$' },
    ],
    correct_key: 'D',
    smart_solution_latex: 'Put $x=0$: $y-6=0\\Rightarrow y=6$. Or $y=-2x+6$. Hence the answer is D.',
    common_traps: ['Taking $C$ as intercept', 'Using $x$-intercept instead'],
  },
  {
    id: 3,
    difficulty: 'Easy',
    subtopic: 'two_point_point_slope',
    needs_graph: true,
    graph: {
      x_min: -2, x_max: 8, y_min: -2, y_max: 8,
      lines: [{ id: 'L', A: 1, B: -1, C: -1, label: 'L' }],
      points: [
        { id: 'A', x: 1, y: 2, label: 'A' },
        { id: 'B', x: 4, y: 5, label: 'B' },
      ],
    },
    stem_latex: 'In the figure, $A(1,2)$ and $B(4,5)$ lie on $L$. The equation of $L$ is',
    options: [
      { key: 'A', latex: '$x-y+1=0$' },
      { key: 'B', latex: '$x-y-1=0$' },
      { key: 'C', latex: '$x+y-3=0$' },
      { key: 'D', latex: '$x+y+1=0$' },
    ],
    correct_key: 'A',
    smart_solution_latex: '$m=\\frac{5-2}{4-1}=1$. Point-slope: $y-2=1(x-1)\\Rightarrow x-y+1=0$. Hence the answer is A.',
    common_traps: ['Slope upside down', 'Sign error rearranging'],
  },
  {
    id: 4,
    difficulty: 'Moderate',
    subtopic: 'parallel_perpendicular',
    needs_graph: false,
    graph: { x_min: -5, x_max: 5, y_min: -5, y_max: 5, lines: [], points: [] },
    stem_latex: 'If the straight lines $3x-ky+1=0$ and $2x+3y-4=0$ are perpendicular, then $k=$',
    options: [
      { key: 'A', latex: '$-2$' },
      { key: 'B', latex: '$-\\dfrac{9}{2}$' },
      { key: 'C', latex: '$2$' },
      { key: 'D', latex: '$\\dfrac{9}{2}$' },
    ],
    correct_key: 'C',
    smart_solution_latex: '$m_1=\\frac{3}{k}$, $m_2=-\\frac{2}{3}$. Perp: $\\frac{3}{k}\\cdot(-\\frac{2}{3})=-1\\Rightarrow -\\frac{2}{k}=-1\\Rightarrow k=2$. Hence the answer is C.',
    common_traps: ['Setting product $=1$', 'Sign error on $m_2$'],
  },
  {
    id: 5,
    difficulty: 'Moderate',
    subtopic: 'parallel_perpendicular',
    needs_graph: true,
    graph: {
      x_min: -6, x_max: 6, y_min: -6, y_max: 6,
      lines: [
        { id: 'L1', A: 1, B: 2, C: -2, label: 'L_1' },
        { id: 'L2', A: 1, B: 2, C: 4, label: 'L_2' },
      ],
      points: [],
    },
    stem_latex: 'In the figure, which of the following is true?',
    options: [
      { key: 'A', latex: '$L_1\\perp L_2$' },
      { key: 'B', latex: '$L_1\\parallel L_2$' },
      { key: 'C', latex: '$L_1$ coincides with $L_2$' },
      { key: 'D', latex: 'The slopes of $L_1$ and $L_2$ have opposite signs' },
    ],
    correct_key: 'B',
    smart_solution_latex: 'Both have slope $-\\frac{1}{2}$ but different intercepts $\\Rightarrow$ parallel distinct. Hence the answer is B.',
    common_traps: ['Thinking same slope means coincide', 'Misreading figure steepness'],
  },
  {
    id: 6,
    difficulty: 'Moderate',
    subtopic: 'intersection',
    needs_graph: true,
    graph: {
      x_min: -4, x_max: 8, y_min: -4, y_max: 8,
      lines: [
        { id: 'L1', A: 1, B: 1, C: -5, label: 'L_1' },
        { id: 'L2', A: 1, B: -1, C: -1, label: 'L_2' },
      ],
      points: [{ id: 'P', x: 3, y: 2, label: 'P' }],
    },
    stem_latex: 'In the figure, $L_1$ and $L_2$ intersect at $P$. The coordinates of $P$ are',
    options: [
      { key: 'A', latex: '$(2,3)$' },
      { key: 'B', latex: '$(3,2)$' },
      { key: 'C', latex: '$(1,4)$' },
      { key: 'D', latex: '$(4,1)$' },
    ],
    correct_key: 'B',
    smart_solution_latex: 'Solve $x+y=5$ and $x-y=1$: add $\\Rightarrow 2x=6\\Rightarrow x=3$, $y=2$. Hence the answer is B.',
    common_traps: ['Swapping $x,y$', 'Arithmetic slip'],
  },
  {
    id: 7,
    difficulty: 'Moderate',
    subtopic: 'distance_point_line',
    needs_graph: true,
    graph: {
      x_min: -2, x_max: 8, y_min: -2, y_max: 8,
      lines: [{ id: 'L', A: 3, B: 4, C: -12, label: 'L' }],
      points: [{ id: 'A', x: 0, y: 0, label: 'A' }],
    },
    stem_latex: 'In the figure, the perpendicular distance from $A(0,0)$ to $L: 3x+4y-12=0$ is',
    options: [
      { key: 'A', latex: '$\\dfrac{12}{5}$' },
      { key: 'B', latex: '$\\dfrac{12}{7}$' },
      { key: 'C', latex: '$3$' },
      { key: 'D', latex: '$4$' },
    ],
    correct_key: 'A',
    smart_solution_latex: '$d=\\dfrac{|3(0)+4(0)-12|}{\\sqrt{3^2+4^2}}=\\dfrac{12}{5}$. Hence the answer is A.',
    common_traps: ['Forgetting absolute value', 'Wrong $\\sqrt{A^2+B^2}$'],
  },
  {
    id: 8,
    difficulty: 'Hard',
    subtopic: 'general_form',
    needs_graph: false,
    graph: { x_min: -5, x_max: 5, y_min: -5, y_max: 5, lines: [], points: [] },
    stem_latex: 'The equation of the straight line with slope $-\\frac{2}{3}$ and $y$-intercept $4$, written in the form $Ax+By+C=0$ where $A>0$ and $A,B,C$ are integers with no common factor other than $1$, is',
    options: [
      { key: 'A', latex: '$2x+3y-12=0$' },
      { key: 'B', latex: '$2x-3y+12=0$' },
      { key: 'C', latex: '$2x+3y+12=0$' },
      { key: 'D', latex: '$2x-3y-12=0$' },
    ],
    correct_key: 'A',
    smart_solution_latex: '$y=-\\frac{2}{3}x+4\\Rightarrow 2x+3y-12=0$ with $A>0$. Hence the answer is A.',
    common_traps: ['Wrong sign when clearing denominators', 'Leaving $A<0$'],
  },
  {
    id: 9,
    difficulty: 'Hard',
    subtopic: 'parallel_perpendicular',
    needs_graph: false,
    graph: { x_min: -5, x_max: 5, y_min: -5, y_max: 5, lines: [], points: [] },
    stem_latex:
      'Let $L_1: ax+2y-1=0$ and $L_2: 2x-ay+3=0$, where $a$ is a non-zero real constant. Which of the following must be true?\nI. If $a=2$, then $L_1\\parallel L_2$.\nII. If $a=-2$, then $L_1\\perp L_2$.\nIII. $L_1$ and $L_2$ cannot be coincident for any real $a\\neq 0$.',
    options: [
      { key: 'A', latex: 'I and II only' },
      { key: 'B', latex: 'I and III only' },
      { key: 'C', latex: 'II and III only' },
      { key: 'D', latex: 'I, II and III' },
    ],
    correct_key: 'C',
    smart_solution_latex:
      '$m_1=-\\dfrac{a}{2}$, $m_2=\\dfrac{2}{a}$.\nI: $a=2\\Rightarrow m_1=-1$, $m_2=1$ (perpendicular, not parallel) — false.\nII: $a=-2\\Rightarrow m_1=1$, $m_2=-1$, product $-1$ — true.\nIII: $m_1=m_2$ needs $-a/2=2/a\\Rightarrow a^2=-4$, impossible, so never parallel/coincident — true.\nHence the answer is C.',
    common_traps: ['Mixing parallel/perp conditions', 'Forgetting coincident needs same slope'],
  },
  {
    id: 10,
    difficulty: 'Hard',
    subtopic: 'distance_point_line',
    needs_graph: false,
    graph: { x_min: -5, x_max: 5, y_min: -5, y_max: 5, lines: [], points: [] },
    stem_latex: 'The distance from the point $(1,-2)$ to the straight line $x-2y+k=0$ is $3$. Which of the following is a possible value of $k$?',
    options: [
      { key: 'A', latex: '$-5-3\\sqrt{5}$' },
      { key: 'B', latex: '$-5$' },
      { key: 'C', latex: '$1$' },
      { key: 'D', latex: '$-5+3\\sqrt{5}$' },
    ],
    correct_key: 'D',
    smart_solution_latex:
      '$\\dfrac{|1-2(-2)+k|}{\\sqrt{5}}=3\\Rightarrow |5+k|=3\\sqrt{5}\\Rightarrow k=-5\\pm 3\\sqrt{5}$. One possible value is $-5+3\\sqrt{5}$. Hence the answer is D.',
    common_traps: ['Dropping absolute value', 'Wrong $\\sqrt{1+4}$'],
  },
];
